### PR TITLE
[Bug] Handle clearing of access count logic for dictionary column eviction policy

### PR DESCRIPTION
**Pull request by manishgupta88**
Code Modifications done:
1. Modified code to invoke clear method implementation from dictionary cache. Whenever a query is fired and dictionary cache is getting used, we should take copy and continue. This is required for column to be successfully deleted from LRU cache.
2. Fixed LRU cache issue in which data load and query was executed successfully in case lru cache size was set to 0MB. If LRU cache size is set to zero then default behavior needs to be considered and all columns based on request should be loaded in memory i.e no eviction policy.

### CODE REVIEW

**Comment by Vimal-Das** [comment]
I suggest that we keep track of access count for correctly identifying the memory used by dictionary so that we can correctly adhere to the user configuration of restricting the dictionary cache to a fixed limit.

**Comment by manishgupta88** [comment]
@Vimal-Das ...I have handled the review comments. Kindly review and merge

**Comment by Vimal-Das** [comment]
retest this please

**Comment by Vimal-Das** [comment]
LGTM

**Comment by Vimal-Das** [comment]
Thanks for working on this, Merged to master.

**Pull request merged**
