### PR TITLE
[issue-581]fix the bug of load parse failure when tblname is in carbon's datatype keywords in DDL.

### PR DESCRIPTION
**Pull request by Zhangshunyu**
#581 
1.Solve this bug : #581 
Separate different ddl and dml, which can seperate the keywords and fix the bug of load parse failure when tblname is carbon's datatype keywords in DDL. Actually, all the parse about tablename.Further more, if the ddl is not related to table name, it can still use the CarbonParser to parse.
2.Use base/child class to prevent keyword from over coupling without changing the parse logic.

We introduced so many key words, for example, table name is : "NO_DICTIONARY", it will be parsed by CREATE DDL because we use hive to parse it, but it could not be parsed by LOAD DDL because in our parser it is a key word. This is not reasonable.

### CODE REVIEW

**Comment by Zhangshunyu** [comment]
@ravipesala pls review this code, thank you!

**Comment by gvramana** [comment]
I think these changes are not required, can explain the error, for which this is fixed.

**Comment by Zhangshunyu** [comment]
for example，if the tablename is string/timestamp/no_dictionary…etc，the tablename will be treated as keywords in cafbonparser，and many ddl will be failure.this is incompetable with hive，we should keep the key words seperated to avoid this.

**Comment by Zhangshunyu** [comment]
you can see the testcase i provided

**Comment by gvramana** [comment]
Not required to move to base class, initLexical already will have keywords, needs to validate wrt that

**Comment by Zhangshunyu** [comment]
@gvramana Pls talk with sujith，he will explain this.

**Comment by Zhangshunyu** [comment]
Now，our parser can not parse this ddl：
LOAD DATA INPATH './src/test/resources/tblNameWithKeywordLoad.csv' INTO TABLE
 STRING OPTIONS('DELIMITER'=',', 'QUOTECHAR'= '"')
The table name is STRING，I mean table name not data type

**Comment by Vimal-Das** [comment]
@Zhangshunyu I had a discussion with @gvramana , we think that we should further investigate whether there is any difference when validating the keywords between Hive Parser and Spark Parser.
We need to make both Create Cube and Load Data DDL have consistent behavior.

If I create a Table with Name as Load, Create DDL will succeed, but loading data will fail. This is not expected behaviour. Either Create should fail or create and load both should suceed.

**Comment by Zhangshunyu** [comment]
Maybe we should keep some reserved keywords，who apperenced in BaseCarbonSqlParser

**Comment by Zhangshunyu** [comment]
What should we do now? Our load ddl it different from hive, not like create table DDL.
@Vimal-Das @gvramana 
I mean, now how to handle the DTS?

**Comment by Zhangshunyu** [comment]
@gvramana @sujith71955 
I tested using sparksql, I think sparksql also has this problem,  pls check the following example:
```
> create table cache(a string);
+---------+--+
| result  |
+---------+--+
+---------+--+
No rows selected (0.078 seconds)
```
t> 
```
cache table cache;
Error: org.apache.spark.sql.AnalysisException: cannot recognize input near 'cache' 'table' 'cache'; line 1 pos 0 (state=,code=0)
```

**Pull request closed without merging**
