### PR TITLE
Removed carbondef dependencies from carbon processing

### PR DESCRIPTION
**Pull request by kumarvishal09**
Removed aggregate table loading code 
Removed Merging code
Removed Alter table code 
Removed dependencies from core
Removed older query flow

### CODE REVIEW

**Comment by sraghunandan** [comment]
@ravipesala please review

**Comment by ravipesala** [comment]
I am also refactoring spark module. I am committing to this branch

**Comment by ravipesala** [comment]
I have run Integration test cases in my machine. And in total it passes 998 test cases. In current branch code it passes only 963.

**Comment by ravipesala** [comment]
LGTM.

**Pull request merged**
