### PR TITLE
fixed some scala code style

### PR DESCRIPTION
**Pull request by foryou2030**
1. val defines a fixed value (which cannot be modified)
2. var defines a variable (which can be modified)

fixed all(about 65) the `"var could be a val"`  scala code warnings in the whole project

### CODE REVIEW

**Comment by chenliang613** [comment]
@QiangCai  please review this PR

**Comment by QiangCai** [comment]
LGTM.

**Comment by foryou2030** [comment]
rebased. @ravipesala @QiangCai pls check. thanks

**Comment by QiangCai** [comment]
LGTM

**Comment by foryou2030** [comment]
rebased @QiangCai

**Comment by QiangCai** [comment]
LGTM

**Pull request merged**
