### PR TITLE
[issue-126 issue-81] generate global dict using pre-defined dict from external column file

### PR DESCRIPTION
**Pull request by Jay357089**
issue #126 issue #81 
to support pre-defined dict from external column file, we add Key word COLUMNDICT in option of load DML to define the column name and column file path as below:

LOAD DATA inpath  'D:/inputPath/carbonTest.csv' INTO TABLE carbonTest options( 'COLUMNDICT '='name:D:/Carbon/carbonData/name.csv,sex:D:/Carbon/carbonData/sex.csv')

user needs to set as "column_Name: column_Path", and multiple columns and file paths can be delimited by ",'.

we handle the above DML as below:
1. in LoadCube, set column name and dictionanry file path in carbonLoadModel.
2. get the column name and column file path from carbonLoadModel, test whether the column is exists, then generate new dict using the column file.
3. read the old dictionary file and compare with new dict and remove duplication, then write dict file.
4 if the column data is also provided by fact table, then drop the column data from fact table when generating dict using fact table file.

i have rebased the pr, pls check

### CODE REVIEW

**Comment by Jay357089** [comment]
@sraghunandan @eason-lyx  could you please assign someone to review?

**Comment by eason-lyx** [comment]
@QiangCai Please review this pr.

**Comment by jackylk** [comment]
@Jay357089 please rebase

**Comment by Jay357089** [comment]
@QiangCai @ravipesala @jackylk   pls review.

**Comment by Jay357089** [comment]
close this. do in another pr.

**Pull request closed without merging**
