### PR TITLE
[issue-650]fix the bug of nullpointerexception without showing log message

### PR DESCRIPTION
**Pull request by Zhangshunyu**
#650 
```
> CREATE TABLE test615 (imei string,age int,productdate timestamp,gamePointId double) STORED BY 'org.apache.carbondata.format'  TBLPROPERTIES('DICTIONARY_EXCLUDE'='imei'); 
+---------+--+
| result  |
+---------+--+
+---------+--+

> LOAD DATA inpath 'hdfs://master:9000/SundayData/NOTEXIST.csv' INTO table test615 options ('DELIMITER'=',', 'QUOTECHAR'='\"', 'FILEHEADER'= 'imei,age,productdate,gamePointId');

Error: org.carbondata.processing.etl.DataLoadingException: the input file does not exist: hdfs://master:9000/SundayData/NOTEXIST.csv (state=,code=0)
```

### CODE REVIEW

**Comment by Zhangshunyu** [comment]
@QiangCai @Jay357089 pls review, thank you.

**Comment by QiangCai** [comment]
please show your test results.

**Comment by Zhangshunyu** [comment]
@QiangCai pls check

**Comment by QiangCai** [comment]
LGTM, please rebase.

**Comment by QiangCai** [comment]
retest this please

**Comment by QiangCai** [comment]
OK, merge to master.

**Pull request merged**
