### PR TITLE
[issue-602] fix equals bug of tableinfo & tableschema

### PR DESCRIPTION
**Pull request by Hexiaoqiao**
#602 fix bug of equals method when use instanceof to check if object is an instance of corresponding class..

### CODE REVIEW

**Comment by ravipesala** [comment]
Can one of the admins verify this patch?

**Comment by gvramana** [comment]
retest this please

**Comment by Hexiaoqiao** [comment]
it looks not trigger jenkins to run ut.

**Comment by ravipesala** [comment]
add to whitelist

**Comment by ravipesala** [comment]
retest this please

**Comment by Vimal-Das** [comment]
retest this please

**Comment by Vimal-Das** [comment]
@Hexiaoqiao Can you rebase this?

**Comment by Hexiaoqiao** [comment]
thanks @Vimal-Das for your comments, just rebase it.

**Comment by Hexiaoqiao** [comment]
hi @Vimal-Das,  test fail because type of tableSchema's tableid is changed, i will fix later.

**Comment by Vimal-Das** [comment]
LGTM, Merged to master

**Pull request merged**
