### PR TITLE
[CARBONDATA-90]Struct of array is failing because of complex dimension ordinal

### PR DESCRIPTION
**Pull request by kumarvishal09**
1. Assignment of complex dimension ordinal was not correct as it was not increment and two children was getting same complex dimension ordinal  
2. Second issue was selecting all the block indexes of complex dimension children.

### CODE REVIEW

**Comment by nareshpr** [comment]
LGTM, Please add testcase

**Comment by kumarvishal09** [comment]
@nareshpr added testcases please check

**Comment by sujith71955** [comment]
retest this please

**Comment by sujith71955** [comment]
LGTM

**Pull request merged**
