### PR TITLE
add apache thrift to README.md

### PR DESCRIPTION
**Pull request by QiangCai**

### CODE REVIEW

**Comment by jackylk** [comment]
But I think thrift will be downloaded and user does not need to install thrift by himself, right?

**Comment by QiangCai** [comment]
@jackylk No, maven-thrift-plugin will not downlaod thirft. We need to downlad thirft and add it to path.

**Comment by ravipesala** [comment]
@QiangCai  I don't think it is necessary to add any information to ReadMe file. Maven can take care of downloading and building thrift.  
@manishgupta88 @mohammadshahidkhan why it is required to add `<thriftExecutable>thrift</thriftExecutable>` to format/pom.xml. Even without this also maven is able to build format.jar file.  Please let me know so that I can raise the PR to remove it.

**Comment by QiangCai** [comment]
pls have a look at [Issue-403](https://github.com/HuaweiBigData/carbondata/issues/403)

**Comment by ravipesala** [comment]
@QiangCai  I am not telling it works now. But we can change the build script to make it work without installing thrift. maven will take care of compiling thrift.

**Comment by chenliang613** [comment]
I agree with Ravindra's opinion.

**Comment by QiangCai** [comment]
close this pr

**Comment by QiangCai** [comment]
How to change the build script without installed thrift?

**Comment by ravipesala** [comment]
@QiangCai  sorry, I have overseen it. Even though after I remove `<thriftExecutable>thrift</thriftExecutable> ` from pom.xml, it still looks for thrift in classpath so it is required to have thrift installed in the machine.

**Comment by jackylk** [comment]
Ok. So I am merging this

**Pull request merged**
