### PR TITLE
[Bug] Fix query without data load null pointer exception on hdfs

### PR DESCRIPTION
**Pull request by Zhangshunyu**
When create a table, execute query without data load, it will throws null pointer exception on hdfs.

### CODE REVIEW

**Comment by Zhangshunyu** [comment]
retest this please

**Comment by Zhangshunyu** [comment]
@QiangCai pls review this code, thank you.

**Comment by kumarvishal09** [comment]
retest this please

**Comment by Zhangshunyu** [comment]
retest this please

**Comment by kumarvishal09** [comment]
LGTM

**Pull request merged**
