### PR TITLE
Created test case project

### PR DESCRIPTION
**Pull request by ManoharVanam**
Created test case project with all test cases

### CODE REVIEW

**Comment by ravipesala** [comment]
retest this please

**Comment by kumarvishal09** [comment]
retest this please

**Comment by ravipesala** [comment]
retest this please

**Comment by ravipesala** [comment]
Added tag to non running test case. Once developer fix the failed test case, he can remove the the tag `NonRunningTests` on the test case. 
And added profile to run integration testcase project. By default these tests don't run along with build. User needs to provide profile like `mvn -Pintegration-test clean package`.

**Comment by ravipesala** [comment]
Merging to master.

**Pull request merged**
