### PR TITLE
[issue-581]fix the bug of load parse failure when tblname is in carbon's datatype in DDL

### PR DESCRIPTION
**Pull request by Zhangshunyu**
This solution is spark solution.

### CODE REVIEW

**Comment by Zhangshunyu** [comment]
@QiangCai @gvramana pls check this solution, it is spark's solution.

**Comment by QiangCai** [comment]
Look good for me.

**Comment by Vimal-Das** [comment]
LGTM

**Comment by gvramana** [comment]
LGTM

**Pull request merged**
