### PR TITLE
[Issue-564]  clean the failed log record after drop the failed loaded table

### LINKED ISSUE #564: [Bug] drop the failed loaded table, the failed log record not clean

### PR DESCRIPTION
**Pull request by foryou2030**
fixed #564

### CODE REVIEW

**Comment by foryou2030** [comment]
@QiangCai pls review it. thanks

**Comment by QiangCai** [comment]
LGTM
@gvramana What's your opinion?

**Comment by Vimal-Das** [comment]
LGTM

**Comment by Vimal-Das** [comment]
Merged to master.

**Pull request merged**
