### PR TITLE
Fix gibberish in GenerateDictionaryExample

### PR DESCRIPTION
**Pull request by Jay357089**
in some machine, the result of execute GenerateDictionaryExample will show  gibberish because of using file stream,  i change to another way to get the dictionary.

### CODE REVIEW

**Comment by chenliang613** [comment]
Thanks for you worked on this issue.
I verified, still have some wrong code: @NU#LL$! , please check it.
-------------------------
Dictionary of table:dictSample in database:default
  dimension name: name
    @NU#LL$! Adam Angel Bill David Edward George James John Kevin Maria Mark Mary Michel Paul Peter Sara Sunny 
  dimension name: city
    @NU#LL$! Athens Bangalore Beijing Berlin Boston Chicago Hangzhou NewYork Paris Shanghai Singapore Tokyo Washington

**Comment by Jay357089** [comment]
@chenliang613  "@NU#LL$!" is normal. In case of the null value in the data, we use "@NU#LL$!" to replace it. so, "@NU#LL$!" is a dictionary value representing 'null'.

**Comment by Jay357089** [comment]
@QiangCai @eason-lyx  what is your idea about the format to show dictionary?

**Comment by Jay357089** [comment]
@chenliang613  i discussed with eason and david,  and changed the show  format. maybe fit your meet.

**Comment by QiangCai** [comment]
@Jay357089  please show me running result

**Comment by chenliang613** [comment]
LGTM for the below output:
dictionary of dimension: name
Key			Value
1			@NU#LL$!
2			Adam
3			Angel
4			Bill
5			David
6			Edward
7			George
8			James
9			John
10			Kevin
11			Maria
12			Mark
13			Mary
14			Michel
15			Paul
16			Peter
17			Sara
18			Sunny
**********************************************************************************
dictionary of dimension: city
Key			Value
1			@NU#LL$!
2			Athens
3			Bangalore
4			Beijing
5			Berlin
6			Boston
7			Chicago
8			Hangzhou
9			NewYork
10			Paris
11			Shanghai
12			Singapore
13			Tokyo
14			Washington

**Pull request merged**
