### PR TITLE
[issue-698]fix error message to be proper when table name is given wrong

### PR DESCRIPTION
**Pull request by Zhangshunyu**

### CODE REVIEW

**Comment by Zhangshunyu** [comment]
@QiangCai pls review this pr, thank you!

**Comment by QiangCai** [comment]
please check class AlterTableCompaction also.

**Comment by Zhangshunyu** [comment]
@QiangCai Done, pls check.

**Comment by QiangCai** [comment]
Merge to master. I will raise pr to resolve the comment issue.

**Pull request merged**
