### PR TITLE
[Issue-359] Direct Dictionary Query Flow handling as per the latest impl & [Issue-374] Direct dictionary dataload failure with lenient date parsing

### PR DESCRIPTION
**Pull request by mohammadshahidkhan**
1. [Issue-359] Direct Dictionary Query Flow handling as per the latest impl
2. Corrected the UT failure 
3. [Issue-374] Direct dictionary dataload failure with lenient date parsing

### CODE REVIEW

**Comment by Vimal-Das** [comment]
Please rebase

**Comment by mohammadshahidkhan** [comment]
rebased

**Comment by Vimal-Das** [comment]
retest this please

**Comment by Vimal-Das** [comment]
LGTM, Merged to master.

**Pull request merged**
