### PR TITLE
[CARBONDATA-68] Log Executor Query statistics

### PR DESCRIPTION
**Pull request by kumarvishal09**
added executor side query execution statistics

Message details
Detail Query:
INFO  17-07 03:10:36,236 - [Executor task launch worker-0][partitionID:nest9;queryID:2776118908102_0] Time taken to load the Blocks In Executor for the taskid : 2776118908102_0 Is : 109
INFO  17-07 03:10:36,236 - [Executor task launch worker-0][partitionID:nest9;queryID:2776118908102_0] Time taken to load the Dictionary In Executor for the taskid : 2776118908102_0 Is : 31
INFO  17-07 03:10:36,236 - [Executor task launch worker-0][partitionID:nest9;queryID:2776118908102_0] Time taken to processed 1 block of output record size: 4 for the taskid : 2776118908102_0 Is : 266

Aggregation Query

INFO  17-07 03:11:57,188 - [Executor task launch worker-0][partitionID:nest9;queryID:2856578524673_0] Time taken to load the Blocks In Executor for the taskid : 2856578524673_0 Is : 109
INFO  17-07 03:11:57,188 - [Executor task launch worker-0][partitionID:nest9;queryID:2856578524673_0] Time taken to load the Dictionary In Executor for the taskid : 2856578524673_0 Is : 31
INFO  17-07 03:11:57,188 - [Executor task launch worker-0][partitionID:nest9;queryID:2856578524673_0] Time taken to scan 1 blocks  for the taskid : 2856578524673_0 Is : 31
INFO  17-07 03:11:57,188 - [Executor task launch worker-0][partitionID:nest9;queryID:2856578524673_0] Time take to prepare query result of size 4 for the taskid : 2856578524673_0 Is : 0

Logs are added under "statistic" category to track the time taken and Performance logs.
How ever detailed statistics module has to be added as per #356 , for complete solution.

### CODE REVIEW

**Comment by gvramana** [comment]
Required to add, total number for blocks scanned.

**Comment by gvramana** [comment]
add logger PERF

**Comment by gvramana** [comment]
How about driver side statistics, you can refer likun's PR #356

**Comment by kumarvishal09** [comment]
@gvramana total number of blocks scanned we are printing Time taken to scan 1 blocks for the taskid : 2856578524673_0 Is : 31
add logger PERF- added logger statistic

**Comment by kumarvishal09** [comment]
@gvramana added driver level log

**Comment by kumarvishal09** [comment]
retest this please

**Comment by kumarvishal09** [comment]
@gvramana handled all the comments. Please review and merge

**Pull request merged**
