### PR TITLE
[Issue-649]change  spark-csv 1.4 to spark-csv 1.2

### PR DESCRIPTION
**Pull request by QiangCai**
Code Modifications done:
1. Change to use spark-csv 1.2, Because spark-csv 1.4 will create no task serializable issue on cluster mode. 
link issue #649 
2 .  Modified code to ignore leading and trailing whitespace option in univocity parser and remove trim method from surrogate step while processing a record. (fixed by @manishgupta88 )

### CODE REVIEW

**Comment by QiangCai** [comment]
@gvramana please review

**Comment by Vimal-Das** [comment]
@QiangCai Can you please raise a issue with the exception details of the exception you are getting when using spark-csv1.4

**Comment by Vimal-Das** [comment]
As discussed, there is a bug in spark-csv 1.4 which was upgraded to few days back, hence we are reverting back to spark-cav 1.2

LGTM.

**Comment by Vimal-Das** [comment]
retest this please

**Comment by QiangCai** [comment]
@Vimal-Das I created Issue #649 to show the exception details.

**Comment by Vimal-Das** [comment]
LGTM, @QiangCai can you rebase, i shall merge.

**Comment by QiangCai** [comment]
@Vimal-Das rebase done.

**Comment by gvramana** [comment]
retest this please

**Pull request merged**
