### PR TITLE
fix get file path bug from local machine

### PR DESCRIPTION
**Pull request by eason-lyx**
1.file which has multiple blocks need to skip file path start with 'file:' when data load in local machine.
2.use data.preferredBufferSize

### CODE REVIEW

**Comment by eason-lyx** [comment]
@jackylk this pr for big local file.if add testcase for this ,need to add a big data size csv file.
i have verify in local.

**Comment by gvramana** [comment]
retest this please

**Comment by eason-lyx** [comment]
@gvramana that is a bug in preferredBufferSize, this is no initialize by configuraion.
so currently,always 0. so using data.preferredBufferSize to fix this.
and for local file which has multiple block may has a big size csv file,do i need to add this to test case?

**Comment by kumarvishal09** [comment]
retest this please

**Comment by kumarvishal09** [comment]
retest this please

**Comment by kumarvishal09** [comment]
LGTM

**Pull request merged**
